# Generated by Django 4.0.4 on 2023-01-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagelocation',
            field=models.ImageField(default='others', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='imagetitle',
            field=models.CharField(default='others', max_length=255),
        ),
    ]
