# Generated by Django 4.0.4 on 2023-01-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_request',
            name='to_date_check',
            field=models.BooleanField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service_request',
            name='to_time_check',
            field=models.BooleanField(blank=True, max_length=100, null=True),
        ),
    ]
