# Generated by Django 4.0.4 on 2023-01-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pi',
            field=models.ImageField(blank=True, upload_to='images/pi'),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, upload_to='images/signatures'),
        ),
    ]
