# Generated by Django 4.0.4 on 2023-01-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0002_user_pi_user_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='imagelocation',
        ),
    ]
