# Generated by Django 3.2.13 on 2024-08-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0002_user_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='execution_log',
        ),
    ]
