# Generated by Django 4.0.4 on 2023-01-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0002_user_imagelocation_user_imagetitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='imagetitle',
            new_name='image1',
        ),
    ]
