# Generated by Django 4.0.4 on 2023-01-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0003_rename_imagetitle_user_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagelocation',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
