# Generated by Django 3.2.13 on 2024-08-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0003_delete_execution_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='execution_log',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_no_empid', models.CharField(max_length=100)),
                ('request_no', models.CharField(max_length=100)),
                ('executed_by', models.CharField(max_length=100)),
                ('executed_by_timestamp', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.CharField(max_length=100, null=True)),
                ('approved_by_timestamp', models.DateTimeField()),
                ('job_description', models.CharField(max_length=100, null=True)),
                ('execution_status', models.CharField(max_length=100, null=True)),
                ('execution_remarks', models.CharField(max_length=100, null=True)),
                ('revoke_date_time', models.DateTimeField()),
                ('revoked_by', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
