# Generated by Django 4.0.4 on 2023-01-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0004_alter_service_request_to_time_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_request',
            name='to_date_check',
            field=models.BooleanField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='service_request',
            name='to_time_check',
            field=models.BooleanField(default=False, max_length=100),
        ),
    ]
