# Generated by Django 4.0.4 on 2023-01-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0004_alter_user_imagelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image1',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
