# Generated by Django 3.2.13 on 2024-08-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0004_execution_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution_log',
            name='approved_by_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='execution_log',
            name='revoke_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
