# Generated by Django 4.0.4 on 2023-01-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0005_alter_service_request_to_date_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_request',
            name='from_time',
            field=models.TimeField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service_request',
            name='to_date',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service_request',
            name='to_time',
            field=models.TimeField(max_length=100, null=True),
        ),
    ]
