# Generated by Django 4.0.4 on 2023-01-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0006_alter_service_request_from_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_request',
            name='approved_by_CISO',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service_request',
            name='approved_by_CTO',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service_request',
            name='approved_by_HOB',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service_request',
            name='service_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
