# Generated by Django 4.0.4 on 2023-01-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0007_service_request_approved_by_ciso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_request',
            name='application_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
