# Generated by Django 4.0.4 on 2023-01-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0008_service_request_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_request',
            name='application_status',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
    ]
