# Generated by Django 4.0.4 on 2023-02-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0011_operations_log_status_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_code',
            name='forwarded_to',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
