# Generated by Django 4.0.4 on 2023-02-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0013_alter_service_request_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='network_analysts_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_analyst_employee_id', models.CharField(max_length=100, null=True)),
                ('network_analyst_name', models.CharField(max_length=100, null=True)),
                ('network_analyst_email', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
