# Generated by Django 4.0.4 on 2023-11-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0014_network_analysts_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_request_form_67',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_request_id', models.CharField(max_length=100, null=True)),
                ('service_title', models.CharField(max_length=200, null=True)),
                ('request_no', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('employee_name', models.CharField(max_length=100)),
                ('branch_code', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=100)),
                ('branch_division_name', models.CharField(max_length=100)),
                ('pa_no', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('self_type', models.CharField(blank=True, choices=[('self', 'Self'), ('selfwithservice', 'Self with Service'), ('serviceprovider', 'Service Provider'), ('team', 'Team'), ('visitor', 'Visitor')], max_length=100)),
                ('from_date', models.DateField(blank=True, max_length=100)),
                ('to_date', models.DateField(max_length=100, null=True)),
                ('to_date_check', models.BooleanField(default=False, max_length=100)),
                ('from_time', models.TimeField(max_length=100, null=True)),
                ('to_time', models.TimeField(max_length=100, null=True)),
                ('to_time_check', models.BooleanField(default=False, max_length=100)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('details', models.CharField(blank=True, max_length=100)),
                ('vendor_name', models.CharField(blank=True, max_length=100)),
                ('name1', models.CharField(blank=True, max_length=100)),
                ('contact_number1', models.CharField(blank=True, max_length=100)),
                ('name2', models.CharField(blank=True, max_length=100)),
                ('contact_number2', models.CharField(blank=True, max_length=100)),
                ('approved_by_HOB', models.CharField(default='No', max_length=100, null=True)),
                ('approved_by_CISO', models.CharField(default='No', max_length=100, null=True)),
                ('approved_by_CTO', models.CharField(default='No', max_length=100, null=True)),
                ('application_status', models.IntegerField(default='0', max_length=100, null=True)),
            ],
        ),
    ]
