# Generated by Django 4.0.4 on 2023-11-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0015_service_request_form_67'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_request',
            name='chng_exec_req_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request',
            name='destination_ip',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request',
            name='destination_port',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request',
            name='form_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request',
            name='physical_activity_area',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='service_request',
            name='source_ip',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request',
            name='team_emp_id1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request',
            name='team_emp_id2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request',
            name='team_emp_id3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request',
            name='team_emp_id4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request',
            name='team_lead',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request',
            name='team_lead_epmloyee_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request',
            name='team_name1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request',
            name='team_name2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request',
            name='team_name3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request',
            name='team_name4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request_form_67',
            name='chng_exec_req_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request_form_67',
            name='destination_ip',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request_form_67',
            name='destination_port',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request_form_67',
            name='form_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request_form_67',
            name='physical_activity_area',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='service_request_form_67',
            name='source_ip',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request_form_67',
            name='team_emp_id1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request_form_67',
            name='team_emp_id2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request_form_67',
            name='team_emp_id3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request_form_67',
            name='team_emp_id4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request_form_67',
            name='team_lead',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request_form_67',
            name='team_lead_epmloyee_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request_form_67',
            name='team_name1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request_form_67',
            name='team_name2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request_form_67',
            name='team_name3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service_request_form_67',
            name='team_name4',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
