# Generated by Django 4.0.4 on 2023-12-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0016_service_request_chng_exec_req_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproverList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('approver_level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='execution_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, null=True)),
                ('executed_by', models.CharField(max_length=100, null=True)),
                ('job_description', models.CharField(max_length=100, null=True)),
                ('execution_status', models.CharField(max_length=100, null=True)),
                ('execution_remarks', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
