# Generated by Django 4.0.4 on 2024-03-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0018_servicecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_request',
            name='request_for',
            field=models.CharField(blank=True, choices=[('access', 'Access'), ('service', 'Service')], max_length=100),
        ),
        migrations.AddField(
            model_name='service_request',
            name='tools_device_required',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service_request_form_67',
            name='tools_device_required',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='service_request',
            name='details',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='service_request',
            name='reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='service_request_form_67',
            name='reason',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
