# Generated by Django 3.2.13 on 2024-03-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0019_service_request_request_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_request',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
