# Generated by Django 3.2.13 on 2024-03-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeInfo', '0020_service_request_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution_log',
            name='approved_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='execution_log',
            name='job_ref',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='execution_log',
            name='revoke_date_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='execution_log',
            name='revoked_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
