# Generated by Django 4.1.3 on 2022-11-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchList',
            fields=[
                ('branchCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('branchIpAddress', models.CharField(max_length=10, null=True, unique=True)),
                ('branchName', models.CharField(max_length=200)),
                ('branchAddress', models.CharField(max_length=500, null=True)),
                ('branchMnemonic', models.CharField(max_length=30)),
            ],
        ),
    ]
