# Generated by Django 4.1.3 on 2022-11-23 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0002_branchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermodel.branchlist'),
        ),
    ]
