# Generated by Django 4.1.3 on 2022-12-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0004_alter_user_branch_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('AO', 'ASSISTANT OFFICER'), ('OFF', 'OFFICER'), ('EO', 'EXECUTIVE OFFICER'), ('SEO', 'SENIOR EXECUTIVE OFFICER'), ('PO', 'PRINCIPAL OFFICER'), ('FAVP', 'FIRST ASSISTANT VICE PRESIDENT'), ('AVP', 'ASSISTANT VICE PRESIDENT'), ('FVP', 'FIRST VICE PRESIDENT'), ('VP', 'VICE PRESIDENT'), ('SVP', 'SENIOR VICE PRESIDENT'), ('SEVP', 'SENIOR EXECUTIVE VICE PRESIDENT')], default='AO', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emp_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emp_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_num',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
